files:
  - source: /locales/ko-KR.yml
    translation: /locales/%locale%.yml
    update_option: update_as_unapproved
  - source: /src/docs/ko-KR/**/*.md
    translation: /src/docs/%locale%/**/%original_file_name%
    update_option: update_as_unapproved
