contact_links:
  - name: 👪 Misskey Forum
    url: https://forum.misskey.io/
    about: Ask questions and share knowledge
  - name: 💬 CherryPick official Discord
    url: https://discord.gg/V8qghB28Aj
    about: Chat freely about CherryPick
